services:
  mobility-discovery-service:
    build: ./discovery-service
    container_name: mobility-discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]

  mobility-config-service:
    build: ./config-service
    container_name: config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    depends_on:
      mobility-discovery-service:
        condition: service_healthy