services:
#  mobility-discovery-service:
#    build: ./discovery-service
#    container_name: mobility-discovery-service
#    ports:
#      - '8761:8761'
#    expose:
#      - '8761'
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
#
#  mobility-config-service:
#    build: ./config-service
#    container_name: mobility-config-service
#    ports:
#      - '9999:9999'
#    expose:
#      - '9999'
#    environment:
#      - DISCOVERY_SERVICE_URL=http://mobility-discovery-service:8761/eureka
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
#    depends_on:
#      mobility-discovery-service:
#        condition: service_healthy
#  mobiliy-user-service:
#    build: ./user-service
#    container_name: mobility-user-service
#    ports:
#      - '8081:8081'
#    expose:
#      - '8081'
#    environment:
#      - DISCOVERY_SERVICE_URL=http://mobility-discovery-service:8761/eureka
#      - CONFIG_SERVICE_URL=http://mobility-config-service:9999
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
#    depends_on:
#      mobility-config-service:
#        condition: service_healthy
#  mobiliy-gateway-service:
#    build: ./gateway-service
#    container_name: mobility-gateway-service
#    ports:
#      - '8888:8888'
#    expose:
#      - '8888'
#    environment:
#      - DISCOVERY_SERVICE_URL=http://mobility-discovery-service:8761/eureka
#      - CONFIG_SERVICE_URL=http://mobility-config-service:9999
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
#    depends_on:
#      mobiliy-user-service:
#        condition: service_healthy
  mobiliy-achat-service:
    build: ./achat-service
    container_name: mobility-achat-service
    ports:
      - '8082:8082'
    expose:
      - '8082'
    environment:
      - DISCOVERY_SERVICE_URL=http://mobility-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://mobility-config-service:9999
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '80:80'
    expose:
      - '80'
    environment:
      - API_ACHATS_URL=http://localhost:8888/api/achats