services:
  mobility-achat-service:
    build: ./achat-service
    container_name: mobility-achat-service
    environment:
      - FICHIERS_JUSTIFICATIFS_CHEMIN_ROOT = "/mobility"
    ports:
      - '8082:8082'
    expose:
      - '8082'

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '80:80'
    expose:
      - '80'
    environment:
      - API_ACHATS_URL=http://mobility-achat-service:8082/api/achats
      - API_KEYCLOAK_URL=http://keycloak_web:8080/