spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowdHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE