spring:
  cloud:
    gateway:
        routes:
          - id: r1
            uri: lb://USER-SERVICE
            predicates:
              - Path=/api/userEntities/**
          - id : r2
            uri: lb://ACHAT-SERVICE
            predicates:
              - Path=/api/achats/**
        globalcors:
          cors-configurations:
            '[/**]':
              allowedOrigins: "*"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
              allowedHeaders: "*"