version: "3.8"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.6
    container_name: keycloak-server
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
